### ISSUE TITLE
Revise: "help the city avoid flooding" text

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#100]
We need the final draft of this copy from Laura by Febuary 1st so that we have time to update it.

**Comment by dsummersl** [comment]
From Laura:

> Text for blue box (that currently says “Help the city avoid flooding…”): 
“Prevent storm drain pollution by clearing leaves, dirt, litter, and other debris around City storm drains. Click to learn what this means.”
No changes to the text on the pop up screen when you click on the blue box.

**Comment by dsummersl** [comment]
Template is here: https://github.com/codefordurham/adopt-a-drain/blob/production/app/views/sidebar/_guidelines.html.haml

**Comment by ssciere** [comment]
I could not find the text that currently says “Help the city avoid flooding… in the template noted above.  I I will search other templates...

**Comment by dsummersl** [comment]
Oh, I'm sorry...this text is here: https://github.com/codefordurham/adopt-a-drain/blob/fb9980214f00cf3b218dda4f63a0acd4db921c67/config/locales/en.yml#L38

**Comment by ssciere** [comment]
Thanks Dane for the updated link.  It looks like I might not have permissions to change this code (@adopt-a-drain/config/locales/en.yml)  I'm getting a message "you must be on a branch to make or propose changes to this file."

**Comment by ssciere** [comment]
please disregard last message about not having permissions to edit adopt-a-drain/config/locales/en.yml.  I appear to have found a way to make the change.

**Comment by ssciere** [comment]
This is ready to be reviewed for closeout.  Note - The requested update seemed to have an improper capitalization of the C in "City."  I made the C lowercase.  Please let me know if it should be uppercase.  Thanks!

**Comment by dsummersl** [comment]
Looks good!
