### ISSUE TITLE
Revise: "learn more" text.

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#101]
We need the final draft of this copy from Laura by February 1st so that we have time to update it.

**Comment by dsummersl** [comment]
From Laura:

> Introduction 
The Adopt a Drain Durham program enables Durham residents to "adopt" one of the city's storm drains or catch basins and pledge to keep it free of leaves, dirt, litter, and other debris. The program helps reduce localized flooding and fosters community engagement by encouraging the public to take an active role in improving their neighborhood. 
Partners 
Code for Durham and other volunteers used a web-based platform called Github to develop the open source web application on Ruby on Rails. Github enabled contributors to work on the project from anywhere in the world. They modeled Adopt a Drain Durham on Boston's Adopt a Hydrant, for which Code for America provided initial development support in 2012. 
Contact 
Email questions and feedback to stormwatereducation@durhamnc.gov.

**Comment by dsummersl** [comment]
Introduction, Partners and Contact as headers, with appropriate padding.

**Comment by dsummersl** [comment]
Template is here: https://github.com/codefordurham/adopt-a-drain/blob/production/app/views/sidebar/_background.html.haml

**Comment by ssciere** [comment]
I've updated the code with the new text and email address that has been provided.  It appears there is still some text marked as needing an update, but I don't see any next provided.  I'll check in with Dane on Tue 2/19 about this.

**Comment by ssciere** [comment]
I'll plan to check with Dane on this one at the March 5th CFD meeting.

**Comment by dsummersl** [comment]
I cleaned up an extra paragraph and mailto, looks good!
