### ISSUE TITLE
Remove 'Drains to Ocean/Bay' from map legend

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#35]
We don't have ocean/bay.

**Comment by tjdev7** [comment]
I can't find in the search box, but tt should be around either inside the modal box or the button div: 

<div id='legend'>
<div class='title'>
Legend
</div>
<div class='show-hide'>
<a href='#' id='toggleLegend'>
Hide
</a>
</div>
</div>
</div>
</div>
<div class='modal fade' id='tos'>
<div class='modal-dialog modal-lg'>
<div class='modal-content'>
<div class='modal-header'>
<button aria-label='Close' class='close' data-dismiss='modal' href='#' type='button'>
<span aria-hidden='true'>
&times;
</span>
</button>
