### ISSUE TITLE
Review 'Terms of Service' link text

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#49]

**Comment by dsummersl** [comment]
It is a little difficult to find the terms of service copy:

1. Go to https://adoptadraindurham.herokuapp.com/
2. (sign out if your signed in )
3. Register/sign-in
4. Just above the "Sign Up" button, click on the link here: By signing up, you agree to the Terms of Service.

**Comment by shanewilliams02** [comment]
I reviewed TOS found one typo and fixed (5/30/17)
