### ISSUE TITLE
Pull drain location data from the Durham Open Data portal

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#50]
Sam McClain says the drain data is on the portal and recently updated for us.

**Comment by specious** [comment]
According to [Stormwater Drains > Information](https://opendurham.nc.gov/explore/dataset/stormwater-drains/information/), the data was "modified" by the City and County of Durham, NC on March 9, 2015 and "last processing" was on October 8, 2017:

![durham-stormwater-dataset-information](https://user-images.githubusercontent.com/451178/31408052-309b4b40-add5-11e7-8629-2840aeab9c6c.png)

Do we know what, specifically, is implied by "modified" and "last processing"?

**Comment by specious** [comment]
We have a rake task that used to retrieve storm drain location data [from the public works ArcGIS server](https://github.com/codefordurham/adopt-a-drain/blob/9e9e521c750c30e37f52c47d98fac7737f4a66ed/lib/tasks/data.rake#L12), but it doesn't work any more:

```
$ bundle exec rake data:download_csv
(in /Users/specious/Dropbox/System/code4/adopt-a-drain/src)
Downloading CSV data...
uri: http://gisweb2.durhamnc.gov//ArcGIS/rest/services/PublicWorks/PublicWorks/MapServer/46/query?f=json&returnGeometry=true&outSR=4326&outFields=TASK,FORM,OPERATIONALAREA,FACILITYID,LOCATION,OWNER,STATUS,COMMENT,TYPE&where=OWNER%3D%27CITY-ROW%27%20and%20STATUS%3D%27EXISTING%27%20and%20TASK%3D%27INLET%27&returnIdsOnly=true
rake aborted!
NoMethodError: undefined method `each_slice' for nil:NilClass
/Users/specious/Dropbox/System/code4/adopt-a-drain/src/lib/tasks/data.rake:19:in `block (2 levels) in <top (required)>'
Tasks: TOP => data:download_csv
(See full trace by running task with --trace)

$ curl http://gisweb2.durhamnc.gov//ArcGIS/rest/services/PublicWorks/PublicWorks/MapServer/46/query\?f\=json\&returnGeometry\=true\&outSR\=4326\&outFields\=TASK,FORM,OPERATIONALAREA,FACILITYID,LOCATION,OWNER,STATUS,COMMENT,TYPE\&where\=OWNER%3D%27CITY-ROW%27%20and%20STATUS%3D%27EXISTING%27%20and%20TASK%3D%27INLET%27\&returnIdsOnly\=true
{"error":{"code":500,"message":null,"details":[]}}
```

So we currently rely on a [snapshot](https://github.com/codefordurham/adopt-a-drain/blob/9e9e521c750c30e37f52c47d98fac7737f4a66ed/lib/tasks/data.rake#L34) that we've saved and added to the git repository.

The data is [now available on the Durham Open Data portal](https://opendurham.nc.gov/explore/dataset/stormwater-drains/) and we can either download it as CSV or JSON and import or use the their [new V2 API](https://opendurham.nc.gov/api/v2/console).

That is our goal.
