### ISSUE TITLE
Change legend information 

### ISSUE THREAD

**Issue by tjdev7** [codefordurham/adopt-a-drain#51]
Change legend ‘drains to sewer’ to ‘drains to creek’ for all of Durham

**Comment by specious** [comment]
As a user, I find it confusing that "Drains to sewer" is listed in contrast to "Adopted" and "Adopted by you".

![legend](https://user-images.githubusercontent.com/451178/30773638-784db324-a042-11e7-86de-65669f6914c4.png)

I think "Unadopted" or "Needs adoption" makes more sense.

**Comment by dsummersl** [comment]
Changed to drains to stream.
