### ISSUE TITLE
update the new logos for the city.

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#96]
The City has a new style guide; they would like to use the logo from it instead of what we are using.

 http://durhamnc.gov/3229/City-of-Durham-Brand-Guide

**Comment by dsummersl** [comment]
The logo that will be replaced is in the lower left of this page: https://adoptadrain.codefordurham.com/

**Comment by garrisonreid** [comment]
Attached is a logo on white and without a background. I matched the pixel height/width of the existing image. Thanks.

![durhamcitylogo_2018update_transp](https://user-images.githubusercontent.com/8192653/50985446-51d34a00-14d2-11e9-8a71-7d4141ecd495.png)
![durhamcitylogo_2018update](https://user-images.githubusercontent.com/8192653/50985456-57c92b00-14d2-11e9-9896-18992fdc023f.png)

**Comment by dsummersl** [comment]
Logos are here: https://github.com/codefordurham/adopt-a-drain/tree/production/app/assets/images/logos

**Comment by dsummersl** [comment]
done!
