### ISSUE TITLE
Revise "terms of service" copy

### ISSUE THREAD

**Issue by dsummersl** [codefordurham/adopt-a-drain#99]
We need the final draft of this copy from Laura by Febuary 1st so that we have time to update it.

**Comment by dsummersl** [comment]
[Terms of Service LWS.docx](https://github.com/codefordurham/adopt-a-drain/files/2825093/Terms.of.Service.LWS.docx)

**Comment by dsummersl** [comment]
Template is here: https://github.com/codefordurham/adopt-a-drain/blob/production/app/views/sidebar/_tos.html.haml

**Comment by ssciere** [comment]
The content has been updated.  I'm working on a few corrections to fix some minor spacing issues.

**Comment by ssciere** [comment]
This is ready to be reviewed for closeout.  Thanks!

**Comment by dsummersl** [comment]
Looks good!
